### ISSUE TITLE
Cannot connect using elastic-search

### ISSUE THREAD

**Issue by hazio** [matteodem/meteor-easy-search#116]
For some reason I cannot connect anymore (it has worked before) to my external ES deployment.

Error log:
Elasticsearch ERROR: 2015-01-13T14:54:22Z
  Error: Request error, retrying -- connect ECONNREFUSED
      at Log.error (/ROOT/programs/server/npm/matteodem:easy-search/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/ROOT/programs/server/npm/matteodem:easy-search/node_modules/elasticsearch/src/lib/transport.js:193:18)
      at HttpConnector.<anonymous> (/ROOT/programs/server/npm/matteodem:easy-search/node_modules/elasticsearch/src/lib/connectors/http.js:145:7)
      at ClientRequest.bound (/ROOT/programs/server/npm/matteodem:easy-search/node_modules/elasticsearch/node_modules/lodash-node/modern/internals/baseBind.js:56:17)
      at ClientRequest.emit (events.js:95:17)
      at Socket.socketErrorListener (http.js:1552:9)
      at Socket.emit (events.js:95:17)
      at net.js:441:14
      at process._tickCallback (node.js:442:13)

I can see that the external ES deployment is alive and kicking via curl command. 

Any ideas what is broken?

**Comment by matteodem** [comment]
The leaderboard example works with the right configuration, the error clearly shows that the connection cannot be established. Can you please show your configuration?

**Comment by hazio** [comment]
EasySearch.config({
      'hosts' : [
        	"https://xxx:yyy@aws-eu-west-1-portal0.dblayer.com:10034/",
        	"https://xxx:yyy@aws-eu-west-1-portal1.dblayer.com:10030/"
        ]
});

**Comment by matteodem** [comment]
You surely also got credentials in there right? You might need to host to null since there is some default configuration: https://github.com/matteodem/meteor-easy-search/blob/master/lib/easy-search-server.js#L5. This might fix the problem (since it might take host over hosts).

**Comment by hazio** [comment]
credentials are ok, tested with 'curl https://xxx:yyy@aws-eu-west-1-portal0.dblayer.com:10034/'

**Comment by hazio** [comment]
The fix didn't work. For some reason I can still see the default es host localhost:9200 in logs:

Elasticsearch WARNING: 2015-01-13T15:43:40Z
  Unable to revive connection: http://localhost:9200/

The config looks like this:
        EasySearch.config({
        'hosts' : [
                "https://xxx:yyy@aws-eu-west-1-portal0.dblayer.com:10034/",
                "https://xxx:yyy@aws-eu-west-1-portal1.dblayer.com:10030/"],
        'host' : null
        });

**Comment by hazio** [comment]
update: despite what log says the connection seems to work. So this issue can be closed. Thanks for helping again :)
