### ISSUE TITLE
Version 1.5.4 seems to not work with meteor 1.1.x

### ISSUE THREAD

**Issue by flodragu** [matteodem/meteor-easy-search#185]
When upgrading from Meteor 1.0.4.2 to 1.1.x easy-search also gets updated to 1.5.14 from 1.4.13 and stops working with the exception bellow as it seems (by debugging) that it tries to send the sort value instead of the search value. 
If I downgrade just easy-search to 1.4.13 it starts working again. Any idea if this is something that has a known workaround or fix?

```
Exception from sub usersIndex/easySearch id gDS2Bh8SNtaPXAFR4 MongoError: Can't canonicalize query: BadValue $search needs a String
I20150409-22:39:40.383(-7)?     at Object.Future.wait (/Users/fdragu/.meteor/packages/meteor-tool/.1.1.3.1eoa3br++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150409-22:39:40.384(-7)?     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
I20150409-22:39:40.384(-7)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
I20150409-22:39:40.384(-7)?     at [object Object]._.extend.map (packages/mongo/mongo_driver.js:973:1)
I20150409-22:39:40.384(-7)?     at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:997:1)
I20150409-22:39:40.384(-7)?     at [object Object].Cursor.(anonymous function) (packages/mongo/mongo_driver.js:812:1)
I20150409-22:39:40.384(-7)?     at Object.result.(anonymous function) [as fetch] (packages/edgee:meteor-reactive-publish/lib/reactive-publish.coffee:11:32)
I20150409-22:39:40.384(-7)?     at [object Object].override.fetch (packages/edgee:meteor-reactive-publish/lib/reactive-publish.coffee:56:3)
I20150409-22:39:40.384(-7)?     at [object Object].cursorProto.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/db.js:127:1)
I20150409-22:39:40.385(-7)?     at [object Object].kadira_Cursor_fetch [as fetch] (packages/meteorhacks:kadira/lib/hijack/set_labels.js:75:1)
I20150409-22:39:40.385(-7)?     - - - - -
I20150409-22:39:40.385(-7)?     at Object.toError (/Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20150409-22:39:40.385(-7)?     at /Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:714:54
I20150409-22:39:40.385(-7)?     at Cursor.close (/Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
I20150409-22:39:40.385(-7)?     at commandHandler (/Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:714:21)
I20150409-22:39:40.385(-7)?     at /Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
I20150409-22:39:40.385(-7)?     at Server.Base._callHandler (/Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
I20150409-22:39:40.385(-7)?     at /Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
I20150409-22:39:40.386(-7)?     at [object Object].MongoReply.parseBody (/Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20150409-22:39:40.386(-7)?     at [object Object].<anonymous> (/Users/fdragu/.meteor/packages/mongo/.1.1.0.1o5rhok++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
I20150409-22:39:40.386(-7)?     at [object Object].emit (events.js:95:17)
```

**Comment by matteodem** [comment]
Please show me your configuration for the index? Either it is ```initEasySearch``` or ```createSearchIndex```

**Comment by flodragu** [comment]
EasySearch.createSearchIndex('usersIndex', {
  'field' : ['profile.name','profile.city'],  // required, searchable field(s)
  'collection' : Meteor.users,          // required, Mongo Collection
  'limit' : 5,                  // not required, default is 10
  "use" : "mongo-db",
  'props' : {
    'filteredProximity' : null
  },
  'query' : function (searchString) {
    // Default query that will be used for searching
    var query = EasySearch.getSearcher(this.use).defaultQuery(this, searchString);

    // filter for categories if set
    if (this.props.filteredProximity) {
      query["profile.location"] = {
        $nearSphere: {
           $geometry: this.props.filteredProximity,
           $maxDistance: 100000 // 100 km
        }
      };
    }
    return query;
  }
});

**Comment by vangorra** [comment]
I can attest to this as well. Everything was working fine until a recent update. My issue does not throw an exception. Instead, no results are ever returned. Here is my config:
```javascript
EasySearch.createSearchIndex('DataLegislation', {
    field: ['currentRevision.BillId'],
    collection: Collections.Data.Legislation,
    limit: 20,
    use: 'mongo-db'
});
```
```html
{{> esInput index="DataLegislation" autocomplete="off" }}
{{#esEach index="DataLegislation"}}
..formatting here.
{{/esEach}}

{{#ifEsHasNoResults index="DataLegislation"}}
    <div class="no-results">No results found!</div>
{{/ifEsHasNoResults}}
```

**Comment by matteodem** [comment]
Does downgrading to 1.5.3 / 1.5.2 help? I'll have a look at this soonish

**Comment by matteodem** [comment]
Please update to the latest version of Easy-Search

**Comment by vangorra** [comment]
Confirmed working. Thanks!
