### ISSUE TITLE
How can I search an existing collection defined by a package?

### ISSUE THREAD

**Issue by camstuart** [matteodem/meteor-easy-search#213]
Hi,

I'm using ```meteor add ryw:blog``` which creates it's own collection called ```blog_posts```. 

instead of a traditionally created collection like so:
```JavaScript
Posts = new Meteor.Collection('blog_posts');
Posts.initEasySearch('title');
```
I have to do this:
```JavaScript
// Other operations on Posts seem to work
Posts = Post._collection;

// This fails:
Posts.initEasySearch('title');
```

The error I get is:
```
W20150514-16:50:33.282(10)? (STDERR) /Users/cam/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150514-16:50:33.282(10)? (STDERR) 						throw(ex);
W20150514-16:50:33.282(10)? (STDERR) 						      ^
W20150514-16:50:33.283(10)? (STDERR) TypeError: Object [object Object] has no method 'initEasySearch'
W20150514-16:50:33.283(10)? (STDERR)     at app/lib/collections/posts.js:5:7
W20150514-16:50:33.284(10)? (STDERR)     at app/lib/collections/posts.js:27:3
W20150514-16:50:33.284(10)? (STDERR)     at /Users/cam/sde/meteor-apps/dales-sports-blog/.meteor/local/build/programs/server/boot.js:222:10
W20150514-16:50:33.284(10)? (STDERR)     at Array.forEach (native)
W20150514-16:50:33.284(10)? (STDERR)     at Function._.each._.forEach (/Users/cam/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150514-16:50:33.284(10)? (STDERR)     at /Users/cam/sde/meteor-apps/dales-sports-blog/.meteor/local/build/programs/server/boot.js:117:5
```

Is there a way I can access this existing collection, so I can search the collection?

Thanks

**Comment by matteodem** [comment]
Try `EasySearch.createSearchIndex`, see here: http://matteodem.github.io/meteor-easy-search/docs/javascript-api/.

**Comment by tetiogit** [comment]
I've just added the package ver.1.6.0 to my package and the call to MyCollection.initEasySearch('columnName') does not work for me (i got same error as above). I call the function in the "collection" folder (i.e. seen both on client and server)
