### ISSUE TITLE
Confused as to how to make queries

### ISSUE THREAD

**Issue by afang** [matteodem/meteor-easy-search#406]
After reading the docs I'm still confused as to how to return a specific query when searching. For example, I want to only return `Items.find({owner: Meteor.userId()})`.

```
ItemsIndex = new EasySearch.Index({
  collection: Items,
  fields: ['title'],
  engine: new EasySearch.MongoDB({
  })
});
```

**Comment by matteodem** [comment]
You can use the `selector` method, see the recipes section for an example.

**Comment by afang** [comment]
I want to only display the items where `{owner: userId}`. I'm getting a `ReferenceError: searchObject is not defined`

```
selector(searchDefinition, options) {
      // retrieve the default selector
      var selector = this
      .defaultConfiguration()
      .selector(searchObject, options, aggregation);


      // options.search.userId contains the userId of the logged in user
      selector.owner = options.search.userId;

      return selector;
    }
```

**Comment by matteodem** [comment]
Did you copy this code from the documentation? It needs to be:

```javascript
selector(searchDefinition, options, aggregation) {
      // retrieve the default selector
      var selector = this
      .defaultConfiguration()
      .selector(searchDefinition, options, aggregation);


      // options.search.userId contains the userId of the logged in user
      selector.owner = options.search.userId;

      return selector;
    }
```

**Comment by afang** [comment]
Yes I copied the code from the documentation.

Changed `searchObject` to `searchDefinition` and got `aggregation is not defined`.

```
I20151226-09:07:49.552(-5)? Exception from sub items/easySearch id Gu7oh5oteJYTA8GTd ReferenceError: aggregation is not defined

I20151226-09:07:49.553(-5)?     at MongoDBEngine.EasySearch.Index.engine.EasySearch.MongoDB.selector (lib/collections/items.js:14:44)

I20151226-09:07:49.553(-5)?     at MongoDBEngine.callConfigMethod (lib/core/engine.js:50:19)

I20151226-09:07:49.553(-5)?     at MongoDBEngine.getSearchCursor (lib/engines/mongo-db.js:79:25)

I20151226-09:07:49.553(-5)?     at MongoDBEngine.search (lib/core/reactive-engine.js:104:19)

I20151226-09:07:49.553(-5)?     at [object Object]._handler (lib/core/search-collection.js:173:43)

I20151226-09:07:49.553(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)

I20151226-09:07:49.554(-5)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)

I20151226-09:07:49.554(-5)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)

I20151226-09:07:49.554(-5)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)

I20151226-09:07:49.554(-5)?     at livedata_server.js:548:43

I20151226-09:07:49.562(-5)? Exception from sub items/easySearch id dM6doH3N2p4woGmu8 ReferenceError: aggregation is not defined

I20151226-09:07:49.563(-5)?     at MongoDBEngine.EasySearch.Index.engine.EasySearch.MongoDB.selector (lib/collections/items.js:14:44)

I20151226-09:07:49.563(-5)?     at MongoDBEngine.callConfigMethod (lib/core/engine.js:50:19)

I20151226-09:07:49.563(-5)?     at MongoDBEngine.getSearchCursor (lib/engines/mongo-db.js:79:25)

I20151226-09:07:49.563(-5)?     at MongoDBEngine.search (lib/core/reactive-engine.js:104:19)

I20151226-09:07:49.563(-5)?     at [object Object]._handler (lib/core/search-collection.js:173:43)

I20151226-09:07:49.563(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)

I20151226-09:07:49.563(-5)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)

I20151226-09:07:49.563(-5)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)

I20151226-09:07:49.564(-5)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)

I20151226-09:07:49.564(-5)?     at livedata_server.js:548:43
```

**Comment by afang** [comment]
I removed the `aggregation` parameter and the console is no longer throwing errors, but the items are not being returned to the client.

**Comment by matteodem** [comment]
What you are returning is a mongodb selector, maybe you don't have any `owner` property in your mongo docs?

**Comment by afang** [comment]
The `owner` property exists in Mongo but it looks like the selector.owner is undefined:

```

ItemsIndex = new EasySearch.Index({
  collection: Items,
  fields: ['title', 'owner'],
  engine: new EasySearch.MongoDB({
    sort: function () {
      return { sold: -1 };
    },
    selector(searchDefinition, options) {
      // retrieve the default selector
      var selector = this
      .defaultConfiguration()
      .selector(searchDefinition, options);

      // options.search.userId contains the userId of the logged in user
      console.log(selector.owner, options.search.userId);
      selector.owner = options.search.userId;

      return selector;
    }
  })
});
``` 

undefined:
```
I20151226-09:28:55.693(-5)? { undefined: [ { title: [Object] }, { owner: [Object] } ] } 'p2686PxbiWbBxZkkS'
```

**Comment by allenfuller** [comment]
I'm running into this same problem, trying to filter results. If I put in even the simple MongoDB configuration from the recipes page, I get `ReferenceError: searchObject is not defined`.

In my case, I'd like to filter by a user.profile field to limit results returned to the client.

Here's what I have in the template:
```
  <form class="navbar-form navbar-right hidden-xs navSearchForm" role="search">
    <div class="form-group">
      {{> EasySearch.Input index=ContactsIndex attributes=searchAttributes}}
    </div>
    <div class="navSearchResults hidden">
      <div class="panel panel-default">
        <div class="panel-heading">
          close <button type="button" class="close navSearchClose" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="list-group">
          {{#EasySearch.Each index=ContactsIndex}}
            <a href="/contacts/{{__originalId}}" class="list-group-item">
              <h5 class="list-group-item-heading">{{firstName}} {{lastName}} ({{orgId}}</h5>
            </a>
          {{/EasySearch.Each}}
          <a href="/contacts" class="list-group-item">
            <h4 class="list-group-item-heading">View All Contacts</h4>
            <p class="list-group-item-text">ALL the contacts.</p>
          </a>
        </div>
      </div>
    </div>
  </form>
```
And the helpers:
```
Template.navMain.helpers({
  ContactsIndex: () => ContactsIndex,
  searchAttributes: () => {
    return {
      'class': 'form-control navSearch',
      'placeholder': 'Search Contacts...'
    };
  }
});
```
And then the index:
ContactsIndex = new EasySearch.Index({
  collection: Contacts,
  fields: ['firstName', 'lastName'],
  engine: new EasySearch.MongoDB({
    selector(searchDefinition, options) {
      // retrieve the default selector
      let selector = this
        .defaultConfiguration()
        .selector(searchObject, options, aggregation)
      ;

      console.log('selector:'+JSON.stringify(selector));
      return selector;
    }
  })
});
```
With this setup, I should be able to return results right? If I just use `engine: new EasySearch.MongoDB()` in the index definition, I get results. But the minute I add the selector, it all blows up.

Thanks for any advice. This is a great package and I'm excited to get it up and running!

**Comment by mroftalp** [comment]
I'm confused also. Where will I define the options? I just saw this on the docs

`PlayersIndex.search('Marie', { limit: 5, skip: 10 });`

But doesn't make sense to me when doing search as you press keys. Please enlighten. Thanks!

**Comment by afang** [comment]
@matteodem right now when searching the index returns all items regardless if `owner == Meteor.userId()`. I hope you can provide an example as the documentation is a bit confusing for me.

**Comment by matteodem** [comment]
@afang what you showed me are simple javascript errors that say for example that a variable (aggregation is not defined). As you see in my code snippet I am passing that variable as an argument. 

Can you please re-phrase what your problem is? With a clear description of what the problem is that you're having.
