### ISSUE TITLE
Running search in publish results in, Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.

### ISSUE THREAD

**Issue by vangorra** [matteodem/meteor-easy-search#412]
```
I20160102-15:38:31.149(-8)? Exception from sub PerformFind id 8dHajqbvo2orSLr77 Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20160102-15:38:31.149(-8)?     at AccountsServer.userId (meteor://💻app/accounts_server.js:80:13)
I20160102-15:38:31.149(-8)?     at Object.Meteor.userId (meteor://💻app/accounts_common.js:222:19)
I20160102-15:38:31.149(-8)?     at Index._getSearchOptions (meteor://💻app/lib/core/index.js:83:58)
I20160102-15:38:31.149(-8)?     at Index.search (meteor://💻app/lib/core/index.js:64:20)
I20160102-15:38:31.149(-8)?     at [object Object].Publish.performFind [as _handler] (meteor://💻app/server/Publish:19:77)
I20160102-15:38:31.149(-8)?     at meteor://💻app/packages/check/match.js:103:1
I20160102-15:38:31.150(-8)?     at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
I20160102-15:38:31.150(-8)?     at Object.Match._failIfArgumentsAreNotAllChecked (meteor://💻app/packages/check/match.js:102:1)
I20160102-15:38:31.150(-8)?     at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1695:18)
I20160102-15:38:31.150(-8)?     at [object Object]._.extend._runHandler (meteor://💻app/livedata_server.js:1023:17)
I20160102-15:38:31.150(-8)?     at [object Object]._.extend._startSubscription (meteor://💻app/livedata_server.js:842:9)
I20160102-15:38:31.150(-8)?     at [object Object]._.extend.protocol_handlers.sub (meteor://💻app/livedata_server.js:614:12)
I20160102-15:38:31.150(-8)?     at meteor://💻app/livedata_server.js:548:43
```

``` javascript
function Publish() {}
Publish.prototype.performFind = function(searchString) {
   check(searchString, String);
   return MySearchIndexCollection.search(searchString).mongoCursor;
};

Meteor.publish('PerformFind', Publish.performFind);
```

Looks like the issue is happing at line 83 of index.js in easysearch:core.

``` javascript
  _getSearchOptions(options) {
    return _.defaults(( Meteor.userId ? { userId: Meteor.userId() } : {} ), options, this.defaultSearchOptions);
  }
```

**Comment by vangorra** [comment]
I added a workaround (monkey patch). It avoids the code the triggers the error.

``` javascript
function Publish() {}
Publish.prototype.performFind = function(searchString) {
   check(searchString, String);

   MyCollectionIndex._getSearchOptions = function (options) {
      return _.defaults({ userId: userId }, options, MyCollectionIndex.defaultSearchOptions);
   };

   return MySearchIndexCollection.search(searchString).mongoCursor;
};

Meteor.publish('PerformFind', Publish.performFind);
```

**Comment by vangorra** [comment]
Perhaps depending on this package will do the trick?
https://github.com/peerlibrary/meteor-user-extra

**Comment by matteodem** [comment]
I'll probably add that package as the current syntax is ugly.

**Comment by hyperh** [comment]
Getting the same problem too.

**Comment by matteodem** [comment]
Did you already try adding meteor-user-extra and seeing if that helps? I'll resolve this bug in the core itself soon.

**Comment by hyperh** [comment]
Seems to work with the package meteor-user-extra.

**Comment by jerms** [comment]
Had the same issue, and the package meteor-user-extra, solved this error.

**Comment by postalC** [comment]
same here

**Comment by matteodem** [comment]
Gonna have a look soon:

* make it possible to pass in `userId` as a search option
* check if userId is called anywhere else in code
* update docs

**Comment by matteodem** [comment]
updated example in docs + released new version: http://matteodem.github.io/meteor-easy-search/docs/core/
