### ISSUE TITLE
func.apply is not a function

### ISSUE THREAD

**Issue by JulianKingman** [matteodem/meteor-easy-search#628]
I have a search set up, but it gives me the following error:
```bash
I20171113-08:00:00.703(-5)? Exception from sub links/easySearch id FNubgcTwjoetD9gHq TypeError: func.apply is not a function
I20171113-08:00:00.703(-5)?     at MongoDBEngine.callConfigMethod (packages/easysearch:core/lib/core/engine.js:50:19)
I20171113-08:00:00.704(-5)?     at MongoDBEngine.getFindOptions (packages/easysearch:core/lib/engines/mongo-db.js:74:18)
I20171113-08:00:00.704(-5)?     at MongoDBEngine.getSearchCursor (packages/easysearch:core/lib/engines/mongo-db.js:92:26)
I20171113-08:00:00.704(-5)?     at MongoDBEngine.search (packages/easysearch:core/lib/core/reactive-engine.js:107:19)
I20171113-08:00:00.704(-5)?     at [object Object]._handler (packages/easysearch:core/lib/core/search-collection.js:179:43)
I20171113-08:00:00.704(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171113-08:00:00.705(-5)?     at packages/ddp-server/livedata_server.js:1043:15
I20171113-08:00:00.705(-5)?     at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
I20171113-08:00:00.705(-5)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20171113-08:00:00.705(-5)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20171113-08:00:00.705(-5)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20171113-08:00:00.706(-5)?     at packages/ddp-server/livedata_server.js:559:43
```

My config looks like this:
```javascript
Links = new Mongo.Collection('links');

searchableLinks = new Index({
  collection: Links,
  fields: ['url', 'status', 'notes', 'user'],
  engine: new MongoDBEngine({
    sort: {updatedAt: -1},
    limit(searchObject, options) {
      return options.search.props.limit || 50;
    }
  })
});
```

Template:
```javascript
Template.links.helpers({
    searchableLinks: () => searchableLinks,
});
```
```html
{{#EasySearch.Each index=searchableLinks}}
  <li>data goes here...</li>
{{/EasySearch.Each}}
```

Any ideas what could be wrong?

**Comment by matteodem** [comment]
Try not using the `() =>` shorthand syntax for helpers.
